### ISSUE TITLE
Organizacion Carpetas

### ISSUE THREAD

**Issue by nicolasmiron** [programacion-avanzada/workspace#33]
Sumando al issue #32 que abrió Lucas, sugiero que la distribución debería similar a la siguiente:
- básicas
	- colecciones
	- entrada-salida
	- excepciones
	- lenguaje
- complejidad-computacional
	- metodos de ordenamiento
	- street numbers
- grafos
	- graphs-base
- oia (queda como esta)
- oop-herencia-polimorfismo
	- maquina-de-cafe
	- vehiculos
	- oop-herencia-polimorfismo
-patrones
	- chain-of-responsability
		-chain-of-responsability-1
		-chain-of-responsability-2
	- composite
-programacion-dinamica
-utils

**Comment by delucas** [comment]
Yo creo que los patrones deberían ir por fuera de OOP.
Y la carpeta de utils, a nivel general.
