### ISSUE TITLE
Agregar un ReadMe a Programación Dinámica - ESTHANOSBIEN 

### ISSUE THREAD

**Issue by RrPaulo** [programacion-avanzada/workspace#36]
# Programación Dinámica

Programación dinámica es una técnica matemática que podremos aplicar a problemas que cumplan determinadas condiciones, con el objetivo de mejorar la complejidad computacional de un algoritmo, utilizando determinadas estructuras de datos para almacenar información que nos sea de utilidad en el futuro.

## Solución de Fibonacci con programación dinámica :

**Podemos ver que la solución recursiva  <FibonacciRecursivo.java>, repite múltiples veces los mismos cálculos :**

Para evitar calcular múltiples veces lo mismo, podría ser
una buena alternativa almacenar cada valor de la serie
que ya calculamos, de manera que si necesitamos un
valor que ya hemos calculado previamente, obtenerlo en
O(1).
Solo calcularemos nuevos valores de la serie cuando
nunca antes lo hayamos hecho.

**En la solución de Programación dinámica mejorada <FibonacciPDMejorado.java> :**

Para ello, podemos utilizar un array de Integer
suficientemente grande para almacenar el valor más
grande de la serie que podríamos llegar a necesitar.
Inicializamos nuestro array con los 2 primeros valores de
la serie que conocemos fibo[0]=1, fibo[1]=1. Las
posiciones aún no calculadas tendrán valor null.

**Esta es la idea de la programación dinámica: no calcular dos veces lo mismo💡**

Complejidad Computacional de Fibonacci Recursivo : O(N^6)
Complejidad Computacional de Fibonacci con P.D.   : O(N^4)

**Comment by delucas** [comment]
Me gusta agregar esto al README.
¿El texto es de autoría propia? ¿Se pueden sumar algunas fuentes adicionales?
¿Se podrían sugerir nuevos problemas a resolver con esta técnica?

**Comment by RrPaulo** [comment]
Hola Lucas , mas bien es un resumen o la forma en que yo lo entendi de las clases dictadas. 

Se podría agregar fuentes adicionales para complementar y también nuevos problemas. Lo podría revisar en la semana con tiempo y lo actualizo a tu gusto.

**Comment by delucas** [comment]
Referido en otro issue
