### ISSUE TITLE
[Appol] Sugerencia de mejora: Patrones compuestos

### ISSUE THREAD

**Issue by ManuelR-D** [programacion-avanzada/workspace#39]
Creo que ayudaría al entendimiento de los patrones de diseño, y al uso de los mismos, agregar proyectos donde estos se combinen para un mismo propósito. Por ejemplo en el caso de AmongUs (en el workspace de taller), que se usa Observer para que todos los jugadores auditen a BotonRojo, por como esta el código, se hace lo siguiente
![image](https://user-images.githubusercontent.com/17636012/120896745-36b08a00-c5f9-11eb-8b28-ca32afdf98a6.png)
es evidente la inconveniencia si en vez de 2 jugadores fuera un número más grande, o si hubiera un sub-grupo de jugadores que quisiera auditar un boton específico. En cuyo caso, se podría combinar el patrón Observer con Composite, para crear pelotones de jugadores que tuvieran que observar distintos objetos. Otro ejemplo común podría ser una aplicación del estilo Captura la Bandera, donde cada equipo (que sería un pelotón del Composite) tiene un Observer sobre su bandera para notificar cuándo es capturada.

Creo que ejemplos de este estilo dejarían más en claro la usabilidad de los patrones.

**Comment by delucas** [comment]
Mmm... dos patrones juntos es para complicarlo. Me gustaría ver una implementación del ejemplo CTF.
Se necesitaría un buen README para que esto funcione...
