### ISSUE TITLE
[Oscar La Oveja] PEDIDO DE CAMBIO: Modificar .gitignore

### ISSUE THREAD

**Issue by miroagustin** [programacion-avanzada/workspace#40]
Pedimos modificar el gitignore para también ignorar los .jar, ya que hay un .jar que nos parece que no se entiende para que sirve. Ademas sin ver el commit donde se agrego no sabemos en que ejercicio se utiliza o si hay que utilizarlo en todos los ejercicios.
El archivo se encuentra en https://github.com/programacion-avanzada/workspace/tree/master/utils bajo el nombre de plantuml.jar.
Gracias.

**Comment by delucas** [comment]
Ese archivo se utiliza desde los Makefile de varios proyectos, sirve para armar los diagramas UML.
Lo agregamos al repo para que sea más simple uitilizarlo.
