### ISSUE TITLE
[Oscar la Oveja] SUGERENCIA: OIA Computando Patentes Readme

### ISSUE THREAD

**Issue by miroagustin** [programacion-avanzada/workspace#41]
Para este ejercicio: https://github.com/programacion-avanzada/workspace/tree/master/oia/computando-patentes
Sugerimos agregar un archivo .readme que incluya tanto la consigna del ejercicio como el diagrama de clases y la explicación de la estrategia de resolución.
Gracias.

**Comment by Noorman999** [comment]
#58 Se realizo el diagrama en el issue mencionado

**Comment by delucas** [comment]
Me parece interesante. El diagrama deberíamos hacerlo con plantuml
