### ISSUE TITLE
[Oscar La Oveja] SUGERENCIA: Añadir archivo README en "Armando móviles"

### ISSUE THREAD

**Issue by manu-alde** [programacion-avanzada/workspace#42]
Sugerimos Añadir un archivo README que contenga una descripción de la consigna, una imagen del diagrama de clases y la estrategia para resolver el ejercicio.

Link al proyecto: https://github.com/programacion-avanzada/workspace/tree/master/oia/armando-moviles

**Comment by delucas** [comment]
Me parece bien agregar el README
