### ISSUE TITLE
[Oscar La Oveja] SUGERENCIA: Ejercicio OIA Preparando la receta Readme

### ISSUE THREAD

**Issue by miroagustin** [programacion-avanzada/workspace#44]
Para este repositorio https://github.com/programacion-avanzada/workspace/tree/master/oia/preparando-la-receta
Se sugiere agregar un readme que contenga tanto la consigna como el diagrama de clases y explicación de la estrategia de resolución.
Gracias

**Comment by delucas** [comment]
Me parece bien, todo lo que sea agregar README con más información
