### ISSUE TITLE
Sugerencia de Mejora: Básicas-Colecciones-LYSTP

### ISSUE THREAD

**Issue by JKGarcia94** [programacion-avanzada/workspace#45]
Puntualmente en la explicacion de TreeSet podriamos agregar  que se puede realizar un ordenamiento sin la necesidad de usar un comparator cuando se tratan de tipos de datos basicos y no de objetos, como por ejemplo con Strings,Double etc..

**Comment by delucas** [comment]
Eso es cierto, sin embargo no suele realizarse nunca.
Agreguemos el ejemplo.

**Comment by delucas** [comment]
A este ejemplo podríamos agregarle el uso de `Collections.reverseOrder()`

**Comment by delucas** [comment]
Referido en otro issue
