### ISSUE TITLE
Sugerencia de Mejora: Básicas-Colecciones-LYSTP

### ISSUE THREAD

**Issue by JKGarcia94** [programacion-avanzada/workspace#46]
En los Test  de TreeSet podemos usar un pequeño ejemplo para ver como se realizaría un ordenamiento con Objetos(Actualmente solo hay un test para ordenar con tipo de datos String).

**Comment by delucas** [comment]
Me parece adecuado

**Comment by delucas** [comment]
Referido en otro issue
