### ISSUE TITLE
Sugerencia de mejora: Agregar plantilla pruebas de software - LYSTP

### ISSUE THREAD

**Issue by SchwabMaximiliano** [programacion-avanzada/workspace#47]
Recomiendo agregar una plantilla para facilitar la documentación de los lotes de prueba de software
en https://github.com/programacion-avanzada/workspace/tree/master/basicas-entrada-salida/casos%20de%20prueba

![image](https://user-images.githubusercontent.com/82277824/120903452-92d8d580-c61c-11eb-944a-5d1895804f69.png)

**Comment by delucas** [comment]
Mmm... no es la idea del repo de código
