### ISSUE TITLE
Sugerencia: OOP- Encapsulamiento- LYSTP

### ISSUE THREAD

**Issue by JKGarcia94** [programacion-avanzada/workspace#48]
Se pueden agregar ejemplos prácticos en el código, sobre el uso del ‘Setter’ y visualizar mejor sus beneficios prácticos con respecto al encapsulamiento

**Comment by delucas** [comment]
Cuidado, que encapsulamiento y setter no van de la mano siempre.
¿Qué ejemplos pondrías?

**Comment by JKGarcia94** [comment]
Por el momento, solo tenemos los métodos: contar/Reiniciar/Mostrar. No contamos con alguno que nos permita 'setear' el valor/modificarlo/ o hacer algun cambio dado un parametro de entrada. Por ejemplo podriamos agregar el siguiente metodo:

public void setearContador(int nuevoValor) {		
this.contador = nuevoValor;	
}

tambien se me ocurren agregar mas metodos, donde se pueda ver tambien que al mandar una entrada como parametro se haga alguna modificacion, sin necesidad de acceder directamente al atributo 'contador':  SumarContador/multiplicar/esIgual.
De esta manera, pienso que se podria entender aun mas el uso practico que se le puede dar a este concepto
