### ISSUE TITLE
Sugerencia: OOP- Encapsulamiento-LYSTP

### ISSUE THREAD

**Issue by JKGarcia94** [programacion-avanzada/workspace#49]
Se muestra el bueno uso del modificador de acceso prívate, pero también se podrían implementar ejemplos donde se pueda visualizar el uso de otros modificadores de acceso y así ver en la practica las diferencias al implementarlas, como lo son: ‘package private’, ‘protected’, ‘public’

**Comment by delucas** [comment]
Me parece bien, ¿tenés un ejemplo pensado? No utilicemos ejemplos genéricos, sino un uso particular
