### ISSUE TITLE
Sugerencia: Programacion Dinamica (ejemplos) - Los Apila Bits

### ISSUE THREAD

**Issue by coloco19** [programacion-avanzada/workspace#50]
Se sugiere agregar un apartado con links y/o ejemplos acerca de programacion dinamica

Programacion dinamica:
https://www.instintoprogramador.com.mx/2019/06/programacion-dinamica-en-java.html?m=1

Programacion dinamica con mas ejemplos (ingles):
https://stackabuse.com/dynamic-programming-in-java#levenshteindistance

**Comment by delucas** [comment]
Me gusta, debería ir al README

**Comment by delucas** [comment]
Referido en otro issue
