### ISSUE TITLE
Sugerencia: Funciones Lambda - Los Apila Bits

### ISSUE THREAD

**Issue by coloco19** [programacion-avanzada/workspace#51]
Funciones Lambda: https://www.adictosaltrabajo.com/2015/12/04/expresiones-lambda-con-java-8/
me parecio util este tipo de funciones anonimas, yo personalmente las utilizo cuando quiero ordenar una lista y ya tengo implementado un compareTo() y la quiero ordenar por otro indicador, se puede utilizar esta exprecion Collections.sort(lista, (a,b)-> a-b), donde (a,b)-> a-b es mi funcion lambda anonima que basicamente devuelve a-b (la forma en que va a comprar).
Vale la pena aclarar que tanto "a" como "b" son del tipo de dato que tiene la lista, si mi lista fuera una lista de Casas y yo quiero ordenar por precio deberia usar  Collections.sort(lista, (a,b)-> a.precio-b.precio)

**Comment by delucas** [comment]
Deberíamos agregar un proyecto nuevo con todo el uso de lambdas.
sort, filter, map, groupBy, etc.

**Comment by delucas** [comment]
Referido en otro issue
