### ISSUE TITLE
Sugerencia: Complejidad computacional (ejemplos) - Los Apila Bits

### ISSUE THREAD

**Issue by coloco19** [programacion-avanzada/workspace#55]
Agregar ejemplos extra complejidad computacional
![image](https://user-images.githubusercontent.com/81964683/120905759-a8ed9280-c62a-11eb-8b4d-8723559901c0.png)

![image](https://user-images.githubusercontent.com/81964683/120905774-c6226100-c62a-11eb-8b25-f6fb4273932e.png)

![image](https://user-images.githubusercontent.com/81964683/120905782-d0445f80-c62a-11eb-96e6-92676b1adc45.png)

**Comment by delucas** [comment]
Estos ejemplos deberían estar en un proyecto, y utilizar las fuentes enlazadas al lugar correcto.
Me gusta la idea de crear un nuevo proyecto para hacerlo.
