### ISSUE TITLE
Agregar README en proyecto threads - HenryFor

### ISSUE THREAD

**Issue by agus1355** [programacion-avanzada/workspace#56]
Se podria agregar un README, que incluya una explicacion de que son los threads y cual es su beneficio.

**Comment by AxelJoelCascasi** [comment]
Agrego un link donde explican y hay algunos ejemplos sobre este tema : https://victomanolo.wordpress.com/la-clase-thread/

**Comment by AxelJoelCascasi** [comment]
Ademas, creo que seria util insertar el siguiente diagrama de estados de los threads para entender mejor su funcionamiento :
link : http://3.bp.blogspot.com/-Li6r7FoUe5A/UIFRJKK4_GI/AAAAAAAAAEk/wgcVoICNtDU/s1600/CicloVidaThreadBasico.bmp

**Comment by delucas** [comment]
Esto aplica al taller
