### ISSUE TITLE
Sugerencia: Monticulos - Los Apila Bits

### ISSUE THREAD

**Issue by coloco19** [programacion-avanzada/workspace#57]
Agregar mas informacion acerca de implementacion de monticulos.

Video para montículos: https://www.youtube.com/watch?v=AD_J4ZUheik
Pagina con implementacion y ejemplos: https://aprendeyprogramablog.wordpress.com/2016/10/19/monticulos/

**Comment by delucas** [comment]
Me parece bien, pero deberíamos realizar una implementación propia, correctamente realizada

**Comment by delucas** [comment]
Referido en otro issue
