### ISSUE TITLE
Sugerencia: computando-patentes - Los Apila Bits

### ISSUE THREAD

**Issue by Noorman999** [programacion-avanzada/workspace#58]
Buenas tardes! Realizamos el diagrama de el ejercicio de la OIA 'computando-patentes', ya que nos parece útil cuando alguien esta practicando para el primer parcial,

Ejercicio: https://github.com/programacion-avanzada/workspace/tree/master/oia/computando-patentes

Diagrama:
![computando-patentes](https://user-images.githubusercontent.com/33288453/120904700-ee5a9180-c623-11eb-958a-66a6d8ae2f9c.png)

**Comment by Noorman999** [comment]
Si alguien tiene sugerencias/cambios, avisen por acá así los analizamos y efectuamos!

**Comment by delucas** [comment]
Me parece bien, está referenciado en #41
