### ISSUE TITLE
Pedido de Cambio: computando-patentes - Los Apila Bits

### ISSUE THREAD

**Issue by Noorman999** [programacion-avanzada/workspace#59]
Buenas! Resolviendo ejercicios para practicar y comparando con los resueltos en el repo, se me ocurrio una forma mas limpia y mas corta de resolver el método 'getConversor' de la clase Conversor.

Metodo como esta Actualmente:

```
 public static Conversor getConversor(Patente patente) {
 	Conversor conversor;
 	if (patente.valor.length() == 6) {
		conversor = new Conversor1995(patente);
 	} else {
 		conversor = new Conversor2016(patente);
 	}
 	return conversor;
 }
```

Cambio Sugerido:

```
public static Conversor getConversor(Patente patente) {
	return patente.valor.length() == 6 ? new Conversor1995(patente) : new Conversor2016(patente);
}
```

[Ejercicio](https://github.com/programacion-avanzada/workspace/tree/master/oia/computando-patentes)

[Clase](https://github.com/programacion-avanzada/workspace/blob/master/oia/computando-patentes/src/edu/unlam/progava/patentes/Conversor.java)

Se que no es un gran cambio, pero es mas fácil de entenderlo a primera vista.

Saludos!

**Comment by delucas** [comment]
No me termino de decidir si el cambio es mejor, o peor.
Recurro al juicio de @Federico-G @LucasMPL y @hlanzillotta

**Comment by Federico-G** [comment]
Me parece más claro, pero a la vez estaría bueno que todo el repo este manejado de una manera, que sea siempre la misma. Podría ser ésta
