### ISSUE TITLE
Sugerencia: Implementacion algoritmo Dijkstra - Los Apila Bits

### ISSUE THREAD

**Issue by coloco19** [programacion-avanzada/workspace#60]
Agregar implementacion algoritmo Dijkstra (todo el material esta en ingles)
implementacion con hashset: https://www.baeldung.com/java-dijkstra
implementacion con monticulo: https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-in-java-using-priorityqueue/

**Comment by delucas** [comment]
Me parece bien, pero debemos hacer una implementación propia

**Comment by delucas** [comment]
Referido en otro issue
