### ISSUE TITLE
Sugerencia: agregar Suma de Subrectangulos a PD - HenryFor

### ISSUE THREAD

**Issue by tomasserravento** [programacion-avanzada/workspace#61]
Estaria bueno agregar el codigo de Suma de Subrectangulos asi hay mas ejemplos de Programacion Dinamica ademas del de Fibonacci.

https://miel.unlam.edu.ar/data/contenido/1113/Programacio--n-Dina--mica_1.pdf

**Comment by delucas** [comment]
Me parece adecuado

**Comment by delucas** [comment]
Referido en otro issue
