### ISSUE TITLE
Sugerencia de Mejora: oia - preparando-la-receta - Los Apila Bits

### ISSUE THREAD

**Issue by AgusFG** [programacion-avanzada/workspace#62]
Se sugiere la mejora del ejemplo del ejercicio de la oia, preparando la receta, agregando el diagrama de clases: 

![PreparandoLaReceta](https://user-images.githubusercontent.com/78041597/120905658-f5849e00-c629-11eb-9f99-ebf4fa205053.JPG)

Para el ejemplo: https://github.com/programacion-avanzada/workspace/tree/master/oia/preparando-la-receta

**Comment by delucas** [comment]
Me parece bien, pero debemos hacerlo con plantuml
