### ISSUE TITLE
Reporte / Sugerencia: Instructivo Git - Los Apila Bits

### ISSUE THREAD

**Issue by leanfiorita** [programacion-avanzada/workspace#65]
Buenas profes!
Estuve viendo y en ninguna parte del repo encontre referencia al uso de git.
Encontre en los recursos de loom varios link, entre ellos este https://github.com/delucas/notas/blob/master/anexos/anexo_a_git.md

Adjunto un archivo escrito después de consultar varias fuentes con conceptos básicos y algunos errores frecuentes al usar git.
Entiendo que podría complementarse con el link del repo de lucas y armar un buen documento para que quede para el futuro en el git de la materia

Saludos y espero que sirva 
[Cosas para agregar a la docu de git - LosApilaBits.docx](https://github.com/programacion-avanzada/workspace/files/6603264/Cosas.para.agregar.a.la.docu.de.git.-.LosApilaBits.docx)

**Comment by delucas** [comment]
No es la idea de agregar esto al repo de código, pero lo voy a tener en cuenta para las notas de git.
Gracias!
