### ISSUE TITLE
FRES-GANG Reporte de Error Complejidad Computacional

### ISSUE THREAD

**Issue by FelixSolay** [programacion-avanzada/workspace#66]
En el repositorio “Complejidad Computacional” en el sector de conclusiones hay un error en el ejemplo de las operaciones que se necesitan.
Dice que se requiere un algoritmo de 450 operaciones y las complejidades de los mismos. En el O(n^3) el resultado es incorrecto
Dice que el resultado es: 191,125,000 operaciones. Cuando (450^3) es 91,125,000.

![Error](https://user-images.githubusercontent.com/63932960/120905926-d8e96580-c62b-11eb-81a3-36a05a80a362.jpeg)

Mas abajo dice “…casi doscientos millones!” cuando debería decir “…casi cien millones!”

**Comment by delucas** [comment]
Buen ojo!

**Comment by delucas** [comment]
@Federico-G controlá por las dudas :D

**Comment by Federico-G** [comment]
@delucas Perfecto
