### ISSUE TITLE
FRES-GANG Sugerencia 1 en Entrada/Salida 

### ISSUE THREAD

**Issue by FelixSolay** [programacion-avanzada/workspace#67]
En el titulo: **Creacion de archivo**
El ejemplo parece muy básico y no aporta información clara sobre a que refiere. Creemos que podría ponerse junto con el resto del código, así estaría continuo y seria más entendible.

![Sugerencia1](https://user-images.githubusercontent.com/63932960/120905989-3d0c2980-c62c-11eb-8701-2ba55d115f71.jpeg)

**Comment by delucas** [comment]
Me gustaría ver este cambio para entender qué piensan... ¿podrían elaborar un poco más?

**Comment by delucas** [comment]
Rechazado por no cont estado

**Comment by delucas** [comment]
Referido en otro issue
