### ISSUE TITLE
FRES-GANG Sugerencia 2 en excepciones

### ISSUE THREAD

**Issue by FelixSolay** [programacion-avanzada/workspace#68]
En las explicaciones de las pruebas en vez de nombrarlas como “Prueba 1” “Prueba 2“ y así, se podría poner como nombre el nombre de los @Test “LanzamoslaExcepcion” “AtrapamoslaExcepcion”, etc. O una combinación: “Prueba_1_LanzamoslaExcepcion”, “Prueba_2_AtrapamoslaExcepcion”

**Comment by delucas** [comment]
Me gusta, con el nombre correcto

**Comment by delucas** [comment]
Referido en otro issue
