### ISSUE TITLE
Sugerencia: agregar explicacion sobre costos - HenryFor

### ISSUE THREAD

**Issue by tomasserravento** [programacion-avanzada/workspace#70]
Sugerimos agregar en el readme la explicacion de donde salen los costos de cada metodo de ordenamiento (dice el costo pero no de donde salen)

https://github.com/programacion-avanzada/workspace/tree/master/complejidad-computacional-metodos-de-ordenamiento

**Comment by delucas** [comment]
¿Qué pondrían? ¿Podrían agregar un ejemplo por favor?
