### ISSUE TITLE
[Mick-rosoft] Sugerencia Comentarios Hashcode.java

### ISSUE THREAD

**Issue by thomascu-py** [programacion-avanzada/workspace#77]
Sabemos que en el mundo de la programación hay que aprender mucho de ingles ya que todo esta en ese mismo lenguaje pero  se podría cambiar a español los comentarios ya que no todos tenemos el mismo entendimiento.
Dejo un ejemplo:
workspace/basicas-lenguaje/tests/edu/unlam/progava/lenguaje/HashCodeTests.java

**Comment by delucas** [comment]
Me parece bien, pero no en el código. Lo agregaría, traducido, en el README.
