### ISSUE TITLE
Sugerencia:  Nombres de archivos en Entrada-Salida

### ISSUE THREAD

**Issue by LaraMolina137** [programacion-avanzada/workspace#78]
Los nombres de los archivos in, out y outesperado no son descriptivos.
https://github.com/programacion-avanzada/workspace/tree/master/basicas-entrada-salida/casos%20de%20prueba/

**Comment by delucas** [comment]
¿Qué nombre pondrían?
Me gusta la idea del cambio

**Comment by delucas** [comment]
Rechazado por no contestado

**Comment by delucas** [comment]
Referido en otro issue
