### ISSUE TITLE
Agregar información sobre montículos

### ISSUE THREAD

**Issue by alejanruiz** [programacion-avanzada/workspace#79]
- Agregar ejemplos de montículos junto con las operaciones de agregar y eliminar para ver el impacto en el orden. Se puede usar como referencia la página https://runestone.academy/runestone/static/pythoned/Trees/ImplementacionDeUnMonticuloBinario.html

**Comment by delucas** [comment]
Me gusta la idea

**Comment by delucas** [comment]
Referido en otro issue
