### ISSUE TITLE
Agregar información sobre patrones

### ISSUE THREAD

**Issue by alejanruiz** [programacion-avanzada/workspace#80]
Para muchos los patrones de diseño son un tema nuevo, creo que es necesario una documentación que ejemplifique los más usados, que indique las ventajas, las situaciones donde es más común usarlos. Adjunto documento que puede facilitar el acercamiento para su aprendizaje.
[Introducción a Patrones de diseño.pptx](https://github.com/programacion-avanzada/workspace/files/6603491/Introduccion.a.Patrones.de.diseno.pptx)

**Comment by delucas** [comment]
Me gusta agregar documenetación, pero no en el repo de código.
Agreguemos una breve introducción como un README.
