### ISSUE TITLE
Sugerencia: Falta Ejemplo de Iterator en colecciones

### ISSUE THREAD

**Issue by LaraMolina137** [programacion-avanzada/workspace#81]
En los ejemplos de colecciones falta un ejemplo de iterator, que muestre algún tipo de modificación en una colección que solo puede realizarse en un iterator y no con un foreach.

https://github.com/programacion-avanzada/workspace/tree/master/basicas-colecciones/tests/edu/unlam/progava/colecciones

**Comment by delucas** [comment]
¡Me gusta!

**Comment by delucas** [comment]
Referido en otro issue
