### ISSUE TITLE
Agregar ejemplo de programación dinamica

### ISSUE THREAD

**Issue by alejanruiz** [programacion-avanzada/workspace#82]
Creo que serviría agregar más ejemplos de programación dinámica, por ejemplo el de la pagina https://jcsis.wordpress.com/2013/12/22/programacion-dinamica-algoritmo-cambio-monedas/ que tiene el desarrollo en java.

**Comment by delucas** [comment]
Me parece adecuado

**Comment by delucas** [comment]
Referido en otro issue
